-- create table lecturer (id integer generated by default as identity, age integer not null, name varchar(255), position varchar(255), primary key (id))
INSERT INTO lecturer (age, name, position) VALUES (54, 'Scott Bradley', 'Assistant Professor');
INSERT INTO lecturer (age, name, position) VALUES (32, 'Matthew Smith', 'Instructor');


-- create table student (student_id integer generated by default as identity, birth_place varchar(255), date_of_birth timestamp, gpa integer not null, name varchar(255), primary key (student_id))
INSERT INTO student (birth_place, date_of_birth, gpa, name) VALUES ('London', '1996-04-06', 5.4, 'Anna Broderick');

-- create table subject (id bigint generated by default as identity, credit integer not null, exam boolean, hours_per_week integer not null, name varchar(255), primary key (id))
INSERT INTO subject (credit, exam, hours_per_week, name) VALUES (4, FALSE, 4, 'Introduction to Mathematics');
INSERT INTO subject (credit, exam, hours_per_week, name) VALUES (4, FALSE, 4, 'Introduction to Mathematics');

-- create table subject_lecturer (lecturer_id integer not null, subject_id bigint not null)
INSERT INTO subject_lecturer (lecturer_id, subject_id) VALUES (1, 1);

-- create table course (id bigint generated by default as identity, student_id integer, subject_id bigint, primary key (id))
INSERT INTO course (student_id, subject_id) VALUES (1,1);
INSERT INTO course (student_id, subject_id) VALUES (1,2);